// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ncbfzjrqmndadbvigdeu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5jYmZ6anJxbW5kYWRidmlnZGV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAzNDA5NDUsImV4cCI6MjA1NTkxNjk0NX0.7Rrm1r6QQWq_cK50C8A60M_uCZGlTZlJro3DpsOMnn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);